/**
 * Placeholders: {{BASE_URL}}, {{CLIENT_AREA_URL}}, {{CPANEL_URL_HINT}}, {{WEBMAIL_URL_HINT}},
 * {{SUPPORT_EMAIL}}, {{SUPPORT_PHONE}}, {{SUPPORT_TELEGRAM}}
 * @type {Record<string, string>}
 */
const guides = {
  acct_cpanel_reset: `**Reset cPanel password**\n\n1. Open **{{BASE_URL}}/cpanel-login** — or open the login link from your *Welcome Email*.\n2. Click **Forgot Password**.\n3. Enter the account email registered with GojoHost.\n4. Complete the emailed reset link immediately (links expire).\n\n**Security**\nChoose a unique password not reused on other sites. Enable **two-factor authentication** wherever offered.\n\nIf you receive no mail: check Spam, confirm the correct inbox, try **Webmail**: {{WEBMAIL_URL_HINT}}, or open a ticket with **{{SUPPORT_EMAIL}}**.`,
  acct_plesk_portal_reset: `**Reset Plesk / Client Area password**\n\n**Linux cPanel**\nUses cPanel reset — see *Reset cPanel password*.\n\n**Windows (Plesk)**\n1. Open your Plesk URL from the welcome email (often \`https://host:8443\`).\n2. Use **Forgot your password?** on the Plesk login page.\n\n**Billing / client portal**\n1. Go to **{{CLIENT_AREA_URL}}**.\n2. Use **Forgot password** and the email on file.\n\nStill stuck? Reply with your **domain name** (no passwords) and contact **{{SUPPORT_EMAIL}}**.`,
  acct_cpanel_url: `**cPanel login URL**\n\n• Primary: **{{CPANEL_URL_HINT}}**\n• From client area: **{{CLIENT_AREA_URL}}** → *Services* → *Login to cPanel* if available.\n• Your **Welcome Email** contains the exact hostname and username.\n\n**Tip:** Use HTTPS. If the page does not load, try from another network (mobile data) to rule out local DNS issues.`,
  acct_webmail_url: `**Webmail URL**\n\n• Generic pattern: **{{WEBMAIL_URL_HINT}}** (replace \`yourdomain.com\`).\n• Or in cPanel: **Email** → **Email Accounts** → **Check Email** / **Open Webmail**.\n\nIf Webmail shows certificate warnings, ensure you use the server hostname from your welcome email or install a valid SSL for the mail host.`,
  acct_username: `**Find your hosting username**\n\n1. Search your inbox for **GojoHost** / **Welcome** / **cPanel**.\n2. In cPanel the username appears top-left after login.\n3. In the client area: **{{CLIENT_AREA_URL}}** → your service details.\n\n**Never share** your password in chat. Support may ask for the **domain** and last digits of the registered phone or a recent **invoice ID** to verify you.`,
  acct_change_password_guide: `**Change passwords safely**\n\n**cPanel**\n*Preferences* → **Password & Security** — set a strong password.\n\n**Email accounts**\ncPanel → **Email Accounts** → **Manage** → **Password** for each mailbox.\n\n**FTP**\ncPanel → **FTP Accounts** — update each account.\n\n**MySQL**\ncPanel → **MySQL Databases** — update user password, then update \`wp-config.php\` or app config.\n\nAfter a breach: change **all** of the above and scan files (see *Security & malware*).`,
  acct_recover_credentials: `**Recover lost hosting credentials**\n\n1. Search email for **Welcome** / **New Account** from GojoHost.\n2. Reset cPanel / Client Area using **Forgot password** (see earlier guides).\n3. If the email on file is wrong: contact **{{SUPPORT_EMAIL}}** from an address you control and be ready to verify domain ownership (invoice, ID, or DNS TXT as instructed).\n\nWe **cannot** send full passwords in plain text; we **reset** access after verification.`,
  acct_verify_ownership: `**Verify account ownership before sensitive support**\n\nSupport may require one or more of:\n• Account email + **invoice ID**\n• **Domain** registered on the account\n• Last 4 digits of payment reference / phone on file\n• Temporary **DNS TXT** record at your domain\n• Government / business ID for corporate accounts (when policy requires)\n\nStart verification: type **/verify** in this bot for a short checklist, or email **{{SUPPORT_EMAIL}}** with your domain (no passwords).`,

  dns_domain_setup: `**Point your domain to GojoHost**\n\n1. Get **nameservers** from your welcome email (or ask support).\n2. At your **registrar** (where you bought the domain), replace default NS with GojoHost’s.\n3. Wait for **propagation** (often minutes–48h). Use **/dns yourdomain.com NS** in this bot for a quick check.\n4. In cPanel: **Addon Domains** / **Aliases** as needed.\n\n**Keep DNS at Cloudflare?** Use **A** / **CNAME** to our server IP/hostname per support instructions; avoid proxy issues until the site works.`,
  dns_records: `**Common DNS records**\n\n**A** — hostname → IPv4 of the server.\n**AAAA** — hostname → IPv6 (if provided).\n**CNAME** — alias to another hostname (often \`www\`).\n**MX** — mail servers (priority + hostname). Use values from cPanel **Email Routing** / welcome email.\n**TXT** — SPF/DKIM/DMARC for mail deliverability; domain verification for third parties.\n\nEdit in cPanel **Zone Editor** or your DNS provider. **Lower TTL** (e.g. 300) before big changes to speed up testing.`,
  dns_nameservers: `**Update nameservers**\n\n1. Log in to your **domain registrar**.\n2. Find **DNS** / **Nameservers** → **Custom**.\n3. Enter each GojoHost nameserver on its own line (exact spelling).\n4. Remove old NS if required by the registrar.\n5. Do **not** mix random third-party NS with partial delegation unless you know what you are doing.\n\nNeed the exact values? Check your welcome email or message **{{SUPPORT_TELEGRAM}}**.`,
  dns_propagation: `**Propagation & DNS checks**\n\nDNS is cached worldwide. After changes:\n• Wait and retest with **/dns yourdomain.com A** (and **MX**, **NS**).\n• Try from mobile data vs Wi‑Fi.\n• Flush local DNS if needed (\`ipconfig /flushdns\` on Windows).\n\nThis bot runs a **single-resolver** check — it is not a full global propagation map; use external propagation tools if results differ by region.`,
  dns_addon_subdomain: `**Addon domains & subdomains (cPanel)**\n\n**Addon domain**\ncPanel → **Domains** / **Addon Domains** → add domain → document root (e.g. \`public_html/newsite\`).\n\n**Subdomain**\ncPanel → **Domains** → **Subdomains** → map to a folder under \`public_html\`.\n\nPoint DNS **A** or **CNAME** to the server before expecting the site to load.`,

  web_down: `**Website not loading**\n\n1. **{{BASE_URL}}** / status page if we publish one — else try from another network.\n2. Check **SSL** errors in the browser (click the padlock).\n3. **/dns yourdomain.com A** — does it point to us?\n4. cPanel → **Metrics** → **Errors** for recent issues.\n5. Temporarily rename \`.htaccess\` via File Manager (backup first) if you suspect rules.\n6. Wrong **document root**? Ensure files are under the domain’s folder (\`public_html\` or addon path).\n\nIf others see the site but you do not, it is usually local DNS or cache.`,
  web_500: `**HTTP 500 — Internal Server Error**\n\n1. Read **error_log** in the domain folder or cPanel → **Errors**.\n2. **PHP**: check version in **MultiPHP** matches your app.\n3. Disable new plugins (WordPress: rename \`wp-content/plugins\` selectively).\n4. Fix **permissions** — folders ~755, files ~644 (\`755\` for some caches).\n5. Inspect **.htaccess** for bad directives.\n6. Raise **PHP memory_limit** briefly if logs show exhaustion.\n\nShare the **latest log lines** with support — no passwords.`,
  web_db_conn: `**Database connection errors**\n\n1. Confirm **hostname** (often \`localhost\`; some hosts use a socket/host name from cPanel).\n2. Verify **database name**, **username**, **password** in \`wp-config.php\`, \`.env\`, etc.\n3. Ensure the DB user has **ALL PRIVILEGES** on that database in cPanel → **MySQL® Databases**.\n4. Test login in **phpMyAdmin**.\n5. Disk full? Upgrade/clean disk — MySQL may refuse connections.`,
  web_white_screen: `**White / blank screen**\n\nOften PHP fatals suppressed in production:\n• Enable logging or **WP_DEBUG_LOG** temporarily on WordPress.\n• Switch PHP version.\n• Disable plugins/themes one by one.\n• Ensure **permissions** allow PHP to write to cache folders.\n• Check recently edited files for syntax errors.\n\nCopy **error_log** excerpts to **{{SUPPORT_EMAIL}}**.`,
  web_permissions: `**File permissions**\n\nTypical cPanel/Linux:\n• Directories **755**\n• Files **644**\n• Never **777** on production unless you know why.\n\n**wp-content** uploads may need group write depending on PHP handler — follow app docs.\n\nIf you chmod recursively wrong, restore from backup or ask support.`,
  web_ssl: `**SSL issues**\n\n• Install **SSL** in cPanel **SSL/TLS Status**.\n• Force HTTPS with rules in **.htaccess** or your app — only after the cert is valid.\n• **Mixed content**: update hardcoded \`http://\` links to \`https://\`.\n• **Cloudflare**: set correct SSL mode (often *Full (strict)* with valid origin cert).\n• **Mail**: use the server hostname plus valid mail SSL or appropriate ports (465/587).`,
  web_malware: `**Malware / hack / redirect**\n\n1. Change **all** passwords (cPanel, FTP, DB, app admin).\n2. Run scans: **Immunify** / antivirus in cPanel if included.\n3. Inspect recently modified PHP files (\`grep\`/IDE search for \`eval\`, strange base64).\n4. Restore clean files from **backup** if known good.\n5. Submit clean **reconsideration** to Google Safe Browsing after cleanup.\n\nOur team can assist on **managed** plans — escalate via *Contact & escalation*.`,

  mail_create: `**Create an email account (cPanel)**\n\n1. cPanel → **Email Accounts**.\n2. Choose address, domain, strong password (or generator), quota.\n3. Save — then **Connect Devices** shows IMAP/SMTP settings.\n4. Configure **DKIM / SPF** in **Email Deliverability** to reduce spam tagging.\n\n**Tip:** Separate mailboxes instead of massive catch‑alls.`,
  mail_not_sending: `**Email not sending**\n\n1. Correct **SMTP** host (server hostname vs \`mail.domain.tld\`), port **587** (TLS) or **465** (SSL).\n2. **Authenticate SMTP** — use full email as username.\n3. Check **Outgoing** suspended in cPanel (rate limits).\n4. Try Webmail sending — isolates Outlook/phone vs server.\n5. Review bounce messages for **spam blocklists**.\n\nSend a test to **Mail-Tester.com** — share score with support.`,
  mail_not_receiving: `**Email not receiving**\n\n1. **MX** records → run **/dns yourdomain.com MX**.\n2. cPanel → **Email Routing** = *Local mailbox* unless using external Gmail.\n3. Check **Spam** filter / global filters / forwarders looping.\n4. Disk quota exceeded? Increase or archive mail.\n5. Test inbound from another provider (not same server).`,
  mail_phone_setup: `**Mail on phone or tablet**\n\nUse **automatic** profiles from cPanel **Connect Devices** when possible.\n\n**Incoming IMAP**\n993 SSL or STARTTLS.\n\n**Outgoing SMTP**\n587 STARTTLS preferred; authenticate with mailbox credentials.\n\nOn iOS/Android remove and re‑add account if stuck; verify **certificate trust** accepts our mail hostname.`,
  mail_protocols: `**SMTP / IMAP / POP3**\n\n**IMAP** — mail stays on server (recommended).\n**POP3** — downloads and may delete from server unless configured.\n**SMTP** — always authenticated with your mailbox.\n\nHostnames and ports vary by cluster — copy from **Welcome Email** or cPanel **Connect Devices**.`,
  mail_spam: `**Spam & deliverability**\n\n• Enable **DKIM**, **SPF**, **DMARC** in cPanel where available.\n• Avoid bulk mail from cheap shared IPs if policy forbids.\n• Authenticate SMTP; no open relays.\n• Ask recipients to whitelist your domain.\n• Use transactional providers for newsletters if volume is high.`,
  mail_forward: `**Email forwarding**\n\ncPanel → **Forwarders** → add alias → destination.\n\nWatch for **loops** (A forwards to B, B forwards to A). Prefer **pipes** only if advanced.`,

  cp_upload: `**Upload files**\n\n• **FTP/SFTP**: create account in **FTP Accounts**, use FileZilla/WinSCP.\n• **File Manager**: upload zip then extract (within limits).\n• **SSH** (if allowed on plan): use \`rsync/scp\`.\n\nPublic site files go in correct **document root** (\`public_html\`).`,
  cp_zip: `**Extract ZIP in cPanel**\n\nFile Manager → select \`.zip\` → **Extract**.\nIf extract fails:\n• File too large — split ZIP or upload via FTP uncompressed.\n• Path too long on Windows-created zips.\n• Use terminal/SSH unzip if permitted.`,
  cp_mysql_create: `**Create MySQL database**\n\ncPanel → **MySQL® Databases**:\n1. New database → **Create**\n2. New user → **Create**\n3. **Add user to database** with **ALL PRIVILEGES**\nNote full names include account prefix.`,
  cp_mysql_import: `**Import SQL**\n\n**phpMyAdmin** → select database → **Import** → choose \`.sql\`/\`.sql.gz\`.\n\nLarge dumps: SSH \`mysql\` import, split file, or ask support.\nIncrease **PHP upload/max** briefly if timeouts occur.`,
  cp_ftp: `**FTP accounts**\n\ncPanel → **FTP Accounts** — subdirectory sets chroot boundary.\n\nUse SFTP/FTP SSL when available.`,
  cp_chmod: `**Permissions**\nSee *File permissions*. Use File Manager → **Permissions**.\nRecursive changes can break installs — backup first.`,
  cp_cron: `**Cron jobs**\n\ncPanel → **Cron Jobs**:\nSchedule command e.g.\n/usr/bin/php -q **/home/USER**/path/script.php**\nEnsure paths and PHP binaries match our environment docs.`,
  cp_ssl: `**SSL in cPanel**\n\n**SSL/TLS Status** → Run AutoSSL.\nWildcard/mail SAN may need DV validation — follow prompts.\n\nAfter issue, force HTTPS in app or redirects.`,

  win_aspnet: `**Deploy ASP.NET**\n\n1. Build/publish targeting server **.NET runtime** matching Plesk/IIS docs.\n2. Upload binaries via FTP / Git / Web Deploy if enabled.\n3. Set application pool (**managed pipeline**, **CLR version**) per app.\n4. Enable **HTTPS** binding.\n5. Detailed steps depend on VPS vs shared Windows — follow welcome doc or escalate.`,
  win_mssql: `**MSSQL**\n\n1. Connect from Plesk or SQL Management tools with host/user from welcome email.\n2. Firewall: allow SQL port **only from your IPs**.\n3. Backup before schema changes.`,
  win_webconfig: `**web.config tips**\n\n• URL rewrite rules for HTTPS and pretty URLs.\n• Custom errors temporarily off for diagnostics.\n• **connectionStrings** encrypted or outside repo.\n\nSyntax errors crash the app provider — validate XML.`,
  win_iis_500: `**IIS errors**\n\nEnable **Detailed errors** briefly; check Event Viewer logs (VPS).\nCommon issues: permission on \`site root\`, app pool crash, DLL mismatch.`,
  win_odbc: `**ODBC**\n\nCreate DSN aligned with architecture (64 vs 32 bit) matching your IIS app.\nTest with **ODBC Data Source Administrator** before IIS binding.`,

  res_create_acct: `**Create reseller account (WHM)**\nWHM → **Create a New Account** — domain, pkg, reseller flag if needed.\n\nSet **ownership** correctly for billing vs technical contact.`,
  res_packages: `**Packages / quotas**\nWHM → **Packages** edit disk/bandwidth/databases/feature lists.\n\nKeep packages tight to overselling policy.`,
  res_suspend: `**Suspend / unsuspend**\nWHM → **Manage Account**.\nSuspended sites show suspension page.\n\nDocument reason for auditing.`,
  res_whm: `**WHM basics**\n\n• **Transfers** tools for migrating from other cPanels.\n• **DNS Zones** delegated with care.\n• **Skeleton** configs for templated onboarding.\n• Use **Plugins** sparingly.`,
  res_ns: `**Reseller nameservers**\n\nRegister **glue records** at the registrar pointing child NS to reseller IP.\nAnnounce IP changes *before* cutover.`,

  bill_pay: `**Pay invoice**\n\n1. Login **{{CLIENT_AREA_URL}}**.\n2. **Billing → Invoices** → pay with available methods.\n3. Attach payment confirmation if gateway delays.\n\nOverdue notices may disconnect services automatically per policy.`,
  bill_view: `**View invoices**\n\nUse **{{CLIENT_AREA_URL}}** → **Billing**.\nPDF export if provided.\n\nNeed past years? Export or ticket **{{SUPPORT_EMAIL}}**.`,
  bill_renew_host: `**Renew hosting**\n\nClient area renewal or enable **auto-pay**.\nRenew before suspension date — DNS takes time to reconnect after payment.`,
  bill_renew_domain: `**Renew domain**\n\nRegistrar section in client area.\nWHOIS expiry vs registry lock — renew early to avoid redemption fees.`,
  bill_upgrade: `**Upgrade plan**\n\nOpen ticket or billing → **upgrade** wizard if shown.\nMigrations planned off-peak.`,
  bill_cancel: `**Cancel**\n\nRequest via client area ticket per policy.\nExport backups **before** cancellation date.`,

  bak_create: `**Full backup (cPanel)**\nHome → **Backup** → full / partial backups.\nRespect nightly windows on shared hosting.\n\nFor large sites use SSH \`backup\`/split archives if allowed.`,
  bak_restore_site: `**Restore files**\n\nUse **Backup Wizard** restore or unzip clean copy into docroot after compromise.\n\nVerify DB URLs after restores (WordPress: \`wp_options\`).`,
  bak_restore_db: `**Restore database**\nImport via phpMyAdmin or restore from nightly when available.`,
  bak_download: `**Download**\nBackups saved to homedir or remote — download before rotation deletes them.`,

  sec_scan: `**Malware scan**\nImmunify/AV scans in cPanel; CLI \`clamscan\` on VPS.\n\nQuarantine before delete; false positives happen with obfuscated themes.`,
  sec_infected: `**Infected files**\n\nCompare checksums to official releases; delete unknown PHP in uploads.\nRestore clean core from vendor zip.`,
  sec_account: `**After compromise**\n\nRotate **all** credentials, revoke API keys, review forwarders/cron, patch CMS.`,
  sec_2fa: `**Two-factor authentication**\n\nEnable in **client area** and **cPanel** if available.\nStore recovery codes offline.`,

  vps_m_status: `**Managed — status checks**\n\nOur team monitors uptime. You will receive alerts for planned work.\nFor immediate symptoms: open ticket with **service ID** and timeframe.`,
  vps_m_restart: `**Managed — restart services**\n\nDo **not** reboot production without approval unless policy allows.\nTicket: service, last change, error snippet — we restart web/SQL safely.`,
  vps_m_load: `**Managed — load**\n\nHigh load tickets need \`top\`/\`htop\` screenshots (we collect on our side) and traffic pattern if known (DDoS, cron).`,
  vps_m_web: `**Managed — Apache/Nginx**\n\nShare vhost name, exact URL, and error log tail. We adjust worker limits, PHP-FPM pools, etc.`,
  vps_m_ssl: `**Managed — SSL**\nRequest cert type (Let’s Encrypt vs commercial SAN). Confirm DNS targets before validation.`,
  vps_m_security: `**Managed — hardening**\nFirewall rules, sysctl, Fail2Ban, kernel updates — coordinated in tickets.`,
  vps_u_ssh: `**Unmanaged — SSH**\nssh user@YOUR_IP — key-based login only recommended.\n\nFirst login change root password/disable password auth.`,
  vps_u_stack: `**Unmanaged — LAMP / LEMP**\nFollow distro guides; pin versions.\nSeparate app user from www-data.`,
  vps_u_firewall: `**Unmanaged — UFW**\nufw default deny incoming; allow 22 from your IP before enabling.\n\nOpen 80/443 after web ready.`,
  vps_u_panel: `**Unmanaged — control panel**\nInstall only if licence allows.\nSnapshots before major installs.`,
  esc_human: `**Talk to a human**\n• Email **{{SUPPORT_EMAIL}}**\n• Phone **{{SUPPORT_PHONE}}**\n• Telegram **{{SUPPORT_TELEGRAM}}**\n• Client area: **{{CLIENT_AREA_URL}}**\n• Live chat: **{{BASE_URL}}** → support\n\nPrefer **domain name** + concise issue + steps tried (no passwords).`,
  esc_logs: `**Logs to attach**\n\n• **error_log**, **Apache/Nginx** access tail\n• Latest **PHP** fatal\n• **Mail** bounce headers\n• **Traceroute**/**MTR** to server if unreachable\n• Screenshot with **exact time** timezone\nUse **Pastebin/gist** for long logs.`,
  esc_maintenance: `**Maintenance window**\n\nRequests need lead time. Describe services affected, rollback plan, rollback contact.\nWe schedule low-traffic slices when possible.`,
};

module.exports = { guides };
